### ISSUE TITLE
Contoh Database yang sudah terisi

### ISSUE THREAD

**Issue by Azzammi** [Saifulriza123/sistem-informasi-kepegawaian#2]
Mas saiful, bisa dicantumkan untuk contoh database yang sudah terisi mas.

**Comment by Saifulriza123** [comment]
Gak bisa dimigrasi mas?

**Comment by Azzammi** [comment]
Bisa mas, tapi gak ada file seeder nya. Jadinya sehabis migrasi table
databasenya masih kosong

**Comment by Saifulriza123** [comment]
Oo itu diisi manual aja mas lngsung diprogramnya
